### ISSUE TITLE
Persons without a personCode should not be processed

### ISSUE THREAD

**Issue by Rick-Jongbloed** [Tools4everBV/HelloID-Conn-Prov-Source-Raet-Beaufort-IAM-API#11] opened 2023-07-07 10:26 UTC
Sometimes the API delivers incomplete records. We should not process these records.

**Comment by Rick-Jongbloed** [comment] 2023-07-07 10:27
$persons  | ForEach-Object {
        # Sanitize dataset
        if ($_.personCode -eq $null) { continue }

**Comment by rschouten97** [comment] 2023-07-10 07:35
Closed as duplicate of https://github.com/Tools4everBV/HelloID-Conn-Prov-Source-Raet-Beaufort-IAM-API/issues/8

**Closed by rschouten97** 2023-07-10 07:35 UTC
Labels: duplicate
